# Generated by Django 5.2.8 on 2025-11-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
