# Generated by Django 5.2.8 on 2025-11-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('inwork', 'Принято в работу'), ('done', 'Выполнено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
