# Generated by Django 5.2.8 on 2025-11-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_application_options_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='application',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/', verbose_name='Изображение дизайна'),
        ),
    ]
